import LegalLayout from "@/components/sales/LegalLayout";

export default function DisclaimerPage() {
    return (
        <LegalLayout title="Legal Disclaimer">
            <section className="space-y-6">
                <h2 className="text-2xl font-display font-bold text-white">1. The &quot;Beast&quot; Disclaimer</h2>
                <p>
                    Oraya (Ora) is a high-autonomy system designed for advanced users. It is powerful, aggressive, and direct. It is not a toy. By using Oraya, you acknowledge that you are interacting with a system that can simulate terminal commands and modify your file system at the speed of hardware.
                </p>
            </section>

            <section className="space-y-6">
                <h2 className="text-2xl font-display font-bold text-white">2. No Warranty</h2>
                <p>
                    Oraya is provided &quot;as is.&quot; We make no guarantees that the AI architecture won&apos;t hallucinate a command or suggest a refactor that breaks your build. You are the commander. Always review high-risk terminal commands before authorizing Ora to execute them.
                </p>
            </section>

            <section className="space-y-6">
                <h2 className="text-2xl font-display font-bold text-white">3. Limitation of Liability</h2>
                <p>
                    In no event shall Oraya Technologies or its founder, Anwesh Rath, be liable for any data loss, system failure, or hardware damage resulting from the use or misuse of the software. You operate this beast at your own risk.
                </p>
            </section>

            <section className="space-y-6">
                <h2 className="text-2xl font-display font-bold text-white">4. External Model Output</h2>
                <p>
                    Oraya utilizes third-party large language models. We do not control their outputs. Any opinions, instructions, or code snippets generated by the models do not reflect the views of Oraya Technologies.
                </p>
            </section>
        </LegalLayout>
    );
}
